# AppVeyor 配置文件

image:
  - Visual Studio 2019
  - macOS

# 忽略 Pull Request 的构建
skip_branch_with_pr: true

# Python 版本
stack: python 3.10

# 环境变量（用于 GitHub 发布）
environment:
  GITHUB_TOKEN:
    secure: Ti46nPnZgFh0nRteU6ma0EhJnCTW7PaMn9hnnewZl4gBFPyRQnXNCwGog02+MRLX

# 安装依赖项
install:
  - pip install -r requirements.txt

# 构建脚本
build_script:
  - flet pack main.py --name counter --icon icon.png --product-name counter --product-version "1.2.3" --copyright "Copyright (c) 2022 YourCompany Inc."

# 关闭测试阶段
test: off

# 发布构建产物到 GitHub Releases（仅在 tag 构建时）
deploy:
  provider: GitHub
  auth_token: $(GITHUB_TOKEN)
  on:
    APPVEYOR_REPO_TAG: true

#
# Windows 打包
#
for:
  -
    matrix:
      only:
        - image: Visual Studio 2019

    after_build:
      - 7z a counter-windows.zip %CD%\dist\*.exe

    artifacts:
      - path: counter-windows.zip

#
# macOS 打包
#
  -
    matrix:
      only:
        - image: macOS

    after_build:
      - tar -czvf counter-macos.tar.gz -C dist counter.app

    artifacts:
      - path: counter-macos.tar.gz
