trigger:
  branches:
    include:
      - main
      -
stages:
- stage: winStage
  pool:
    vmImage: 'windows-latest'
  dependsOn: []
  displayName: Windows
  jobs:

  - job: windowsJob
    displayName: Windows
    steps:


    # 安装 Python 和 Flet 依赖
    - task: UsePythonVersion@0
      inputs:
        versionSpec: '3.10'
        addToPath: true

    - script: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pyinstall
      displayName: 'Install Flet and dependencies'

    # 使用 Flet 进行打包，生成 Windows 应用程序
    - task: CmdLine@2
      inputs:
        script: |
          flet pack main.py --add-data "assets;assets"
      displayName: 'Build Flet Application for Windows'


      # 复制生成的 .exe 文件到发布目录
    - task: CopyFiles@2
      displayName: "Copy app to staging directory"
      inputs:
        sourceFolder: '$(Build.SourcesDirectory)/dist'
        contents: '*.exe'
        targetFolder: '$(Build.StagingDirectory)'
        flattenFolders: true

    # 发布 .exe 文件作为构建产物
    - task: PublishBuildArtifacts@1
      displayName: "Publish EXE file"
      inputs:
        PathtoPublish: '$(Build.ArtifactStagingDirectory)'
        ArtifactName: 'Windows_EXE'
        publishLocation: 'Container'
