trigger:
  branches:
    include:
      - main  # 你想要触发构建的分支
      -
stages:
- stage: winStage
  pool:
    vmImage: 'windows-latest'
  dependsOn: []
  displayName: Windows
  jobs:

  - job: windowsJob
    displayName: Windows
    steps:

    # 安装 Flutter SDK
    - task: FlutterInstall@0
      displayName: "Install Flutter SDK"
      inputs:
        mode: 'auto'
        channel: 'stable'
        version: 'latest'

    # 安装 Python 和 Flet 依赖
    - task: UsePythonVersion@0
      inputs:
        versionSpec: '3.10'  # 指定 Python 版本
        addToPath: true

    - script: |
        python -m pip install --upgrade pip
        pip install flet  # 安装 Flet
        pip install -r requirements.txt  # 如果有其他依赖，可以通过 requirements.txt 安装
      displayName: 'Install Flet and dependencies'

    # 运行 Flutter Doctor 以确保 Flutter 环境正确配置
    - task: FlutterCommand@0
      displayName: "Run Flutter diagnostics"
      inputs:
        projectDirectory: '.'
        arguments: 'doctor -v'

    # 使用 Flet 进行打包，生成 Windows 应用程序
    - script: |
        flet build windows  # 打包 Flet 应用程序为 Windows 可执行文件
      displayName: 'Build Flet Application for Windows'

    # 复制生成的 .exe 文件到发布目录
    - task: CopyFiles@2
      displayName: "Copy app to staging directory"
      inputs:
        sourceFolder: '$(Build.SourcesDirectory)/dist'
        contents: '*.exe'
        targetFolder: '$(Build.StagingDirectory)'
        flattenFolders: true

    # 发布 .exe 文件作为构建产物
    - task: PublishBuildArtifacts@1
      displayName: "Publish EXE file"
      inputs:
        PathtoPublish: '$(Build.ArtifactStagingDirectory)'
        ArtifactName: 'Windows_EXE'
        publishLocation: 'Container'
